#!/usr/bin/env bash

_CURDIR="${BASH_SOURCE%/*}"

export REPO_VERITASLC="${_CURDIR}"
export REPO_VERITASLC_PROC="${REPO_VERITASLC}/proc"
export REPO_VERITASLC_DATA="${REPO_VERITASLC}/data"
export REPO_VERITASLC_DATA_PUB="${REPO_VERITASLC_DATA}/pub"
export REPO_VERITASLC_DATA_SRC="${REPO_VERITASLC_DATA}/src"
