name: veritas
channels:
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  '_license=1.1=py27_0'
- !!python/unicode
  'abstract-rendering=0.5.1=np19py27_0'
- !!python/unicode
  'alabaster=0.7.3=py27_0'
- !!python/unicode
  'anaconda=2.3.0=np19py27_0'
- !!python/unicode
  'argcomplete=0.8.9=py27_0'
- !!python/unicode
  'astropy=1.3.2=np112py27_0'
- !!python/unicode
  'babel=1.3=py27_0'
- !!python/unicode
  'backports_abc=0.4=py27_0'
- !!python/unicode
  'bcolz=0.9.0=np19py27_0'
- !!python/unicode
  'beautiful-soup=4.3.2=py27_0'
- !!python/unicode
  'binstar=0.11.0=py27_0'
- !!python/unicode
  'bitarray=0.8.1=py27_0'
- !!python/unicode
  'blaze-core=0.8.0=np19py27_0'
- !!python/unicode
  'blz=0.6.2=np19py27_1'
- !!python/unicode
  'bokeh=0.12.5=py27_0'
- !!python/unicode
  'boto=2.38.0=py27_0'
- !!python/unicode
  'bottleneck=1.0.0=np19py27_0'
- !!python/unicode
  'cairo=1.12.18=4'
- !!python/unicode
  'cdecimal=2.3=py27_0'
- !!python/unicode
  'certifi=14.05.14=py27_0'
- !!python/unicode
  'cffi=1.1.0=py27_0'
- !!python/unicode
  'clyent=0.3.4=py27_0'
- !!python/unicode
  'colorama=0.3.3=py27_0'
- !!python/unicode
  'configobj=5.0.6=py27_0'
- !!python/unicode
  'cryptography=0.9.1=py27_0'
- !!python/unicode
  'curl=7.43.0=0'
- !!python/unicode
  'cython=0.22.1=py27_0'
- !!python/unicode
  'cytoolz=0.7.3=py27_0'
- !!python/unicode
  'datashape=0.4.5=np19py27_0'
- !!python/unicode
  'decorator=4.0.6=py27_0'
- !!python/unicode
  'docutils=0.12=py27_0'
- !!python/unicode
  'dynd-python=0.6.5=np19py27_0'
- !!python/unicode
  'enum34=1.0.4=py27_0'
- !!python/unicode
  'fastcache=1.0.2=py27_0'
- !!python/unicode
  'flask=0.10.1=py27_1'
- !!python/unicode
  'fontconfig=2.11.1=5'
- !!python/unicode
  'freetype=2.5.5=0'
- !!python/unicode
  'funcsigs=0.4=py27_0'
- !!python/unicode
  'futures=3.0.5=py27_0'
- !!python/unicode
  'gevent=1.0.1=py27_0'
- !!python/unicode
  'gevent-websocket=0.9.3=py27_0'
- !!python/unicode
  'greenlet=0.4.7=py27_0'
- !!python/unicode
  'grin=1.2.1=py27_1'
- !!python/unicode
  'h5py=2.5.0=np19py27_3'
- !!python/unicode
  'hdf5=1.8.15.1=1'
- !!python/unicode
  'idna=2.0=py27_0'
- !!python/unicode
  'ipaddress=1.0.7=py27_0'
- !!python/unicode
  'ipykernel=4.2.2=py27_0'
- !!python/unicode
  'ipython=4.0.3=py27_0'
- !!python/unicode
  'ipython-notebook=3.2.0=py27_0'
- !!python/unicode
  'ipython-qtconsole=3.2.0=py27_0'
- !!python/unicode
  'ipython_genutils=0.1.0=py27_0'
- !!python/unicode
  'ipywidgets=4.1.1=py27_0'
- !!python/unicode
  'itsdangerous=0.24=py27_0'
- !!python/unicode
  'jdcal=1.0=py27_0'
- !!python/unicode
  'jedi=0.8.1=py27_0'
- !!python/unicode
  'jinja2=2.8=py27_0'
- !!python/unicode
  'jpeg=8d=0'
- !!python/unicode
  'jsonschema=2.4.0=py27_0'
- !!python/unicode
  'jupyter=1.0.0=py27_3'
- !!python/unicode
  'jupyter_client=4.1.1=py27_0'
- !!python/unicode
  'jupyter_console=4.1.0=py27_0'
- !!python/unicode
  'jupyter_core=4.0.6=py27_0'
- !!python/unicode
  'libdynd=0.6.5=0'
- !!python/unicode
  'libffi=3.0.13=0'
- !!python/unicode
  'libgfortran=3.0.0=1'
- !!python/unicode
  'libpng=1.6.17=0'
- !!python/unicode
  'libsodium=1.0.3=0'
- !!python/unicode
  'libtiff=4.0.2=1'
- !!python/unicode
  'libxml2=2.9.2=0'
- !!python/unicode
  'libxslt=1.1.28=0'
- !!python/unicode
  'llvmlite=0.5.0=py27_0'
- !!python/unicode
  'lxml=3.4.4=py27_0'
- !!python/unicode
  'markupsafe=0.23=py27_0'
- !!python/unicode
  'matplotlib=1.4.3=np19py27_2'
- !!python/unicode
  'mistune=0.7.1=py27_0'
- !!python/unicode
  'mkl=2017.0.1=0'
- !!python/unicode
  'mock=1.0.1=py27_0'
- !!python/unicode
  'multipledispatch=0.4.7=py27_0'
- !!python/unicode
  'nbconvert=4.1.0=py27_0'
- !!python/unicode
  'nbformat=4.0.1=py27_0'
- !!python/unicode
  'networkx=1.9.1=py27_0'
- !!python/unicode
  'nltk=3.0.3=np19py27_0'
- !!python/unicode
  'nose=1.3.7=py27_0'
- !!python/unicode
  'notebook=4.1.0=py27_0'
- !!python/unicode
  'numba=0.19.1=np19py27_0'
- !!python/unicode
  'numexpr=2.6.2=np112py27_0'
- !!python/unicode
  'numpy=1.12.0=py27_0'
- !!python/unicode
  'odo=0.3.2=np19py27_0'
- !!python/unicode
  'openblas=0.2.19=0'
- !!python/unicode
  'openpyxl=1.8.5=py27_0'
- !!python/unicode
  'openssl=1.0.2f=0'
- !!python/unicode
  'pandas=0.19.2=np112py27_1'
- !!python/unicode
  'patchelf=0.8=0'
- !!python/unicode
  'path.py=8.1.2=py27_1'
- !!python/unicode
  'patsy=0.3.0=np19py27_0'
- !!python/unicode
  'pep8=1.6.2=py27_0'
- !!python/unicode
  'pexpect=3.3=py27_0'
- !!python/unicode
  'pickleshare=0.5=py27_0'
- !!python/unicode
  'pillow=2.8.2=py27_0'
- !!python/unicode
  'pip=8.0.2=py27_0'
- !!python/unicode
  'pixman=0.26.2=0'
- !!python/unicode
  'ply=3.6=py27_0'
- !!python/unicode
  'psutil=2.2.1=py27_0'
- !!python/unicode
  'ptyprocess=0.5=py27_0'
- !!python/unicode
  'py=1.4.27=py27_0'
- !!python/unicode
  'py2cairo=1.10.0=py27_2'
- !!python/unicode
  'pyasn1=0.1.7=py27_0'
- !!python/unicode
  'pycosat=0.6.1=py27_0'
- !!python/unicode
  'pycparser=2.14=py27_0'
- !!python/unicode
  'pycrypto=2.6.1=py27_0'
- !!python/unicode
  'pycurl=7.19.5.1=py27_2'
- !!python/unicode
  'pyflakes=0.9.2=py27_0'
- !!python/unicode
  'pygments=2.1=py27_0'
- !!python/unicode
  'pyopenssl=0.15.1=py27_1'
- !!python/unicode
  'pyparsing=2.0.3=py27_0'
- !!python/unicode
  'pyqt=4.11.4=py27_1'
- !!python/unicode
  'pytables=3.2.0=np19py27_0'
- !!python/unicode
  'pytest=2.7.1=py27_0'
- !!python/unicode
  'python=2.7.11=0'
- !!python/unicode
  'python-dateutil=2.4.2=py27_0'
- !!python/unicode
  'pytz=2015.7=py27_0'
- !!python/unicode
  'pywget=2.2=py27_0'
- !!python/unicode
  'pyyaml=3.11=py27_1'
- !!python/unicode
  'pyzmq=15.2.0=py27_0'
- !!python/unicode
  'qt=4.8.7=1'
- !!python/unicode
  'qtconsole=4.1.1=py27_0'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'redis=2.6.9=0'
- !!python/unicode
  'redis-py=2.10.3=py27_0'
- !!python/unicode
  'requests=2.7.0=py27_0'
- !!python/unicode
  'rope=0.9.4=py27_1'
- !!python/unicode
  'runipy=0.1.3=py27_0'
- !!python/unicode
  'scikit-image=0.11.3=np19py27_0'
- !!python/unicode
  'scikit-learn=0.18.1=np112py27_1'
- !!python/unicode
  'scipy=0.18.1=np112py27_1'
- !!python/unicode
  'setuptools=19.6.2=py27_0'
- !!python/unicode
  'simplegeneric=0.8.1=py27_0'
- !!python/unicode
  'singledispatch=3.4.0.3=py27_0'
- !!python/unicode
  'sip=4.16.9=py27_0'
- !!python/unicode
  'six=1.10.0=py27_0'
- !!python/unicode
  'snowballstemmer=1.2.0=py27_0'
- !!python/unicode
  'sockjs-tornado=1.0.1=py27_0'
- !!python/unicode
  'sphinx=1.3.1=py27_0'
- !!python/unicode
  'sphinx_rtd_theme=0.1.7=py27_0'
- !!python/unicode
  'spyder=2.3.5.2=py27_0'
- !!python/unicode
  'spyder-app=2.3.5.2=py27_0'
- !!python/unicode
  'sqlalchemy=1.0.5=py27_0'
- !!python/unicode
  'sqlite=3.9.2=0'
- !!python/unicode
  'ssl_match_hostname=3.4.0.2=py27_0'
- !!python/unicode
  'statsmodels=0.6.1=np19py27_0'
- !!python/unicode
  'sympy=0.7.6=py27_0'
- !!python/unicode
  'system=5.8=2'
- !!python/unicode
  'terminado=0.5=py27_1'
- !!python/unicode
  'theano=0.7.0=np19py27_0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'toolz=0.7.2=py27_0'
- !!python/unicode
  'tornado=4.3=py27_0'
- !!python/unicode
  'traitlets=4.1.0=py27_0'
- !!python/unicode
  'ujson=1.33=py27_0'
- !!python/unicode
  'unicodecsv=0.9.4=py27_0'
- !!python/unicode
  'util-linux=2.21=0'
- !!python/unicode
  'werkzeug=0.10.4=py27_0'
- !!python/unicode
  'wheel=0.26.0=py27_1'
- !!python/unicode
  'xlrd=0.9.3=py27_0'
- !!python/unicode
  'xlsxwriter=0.7.3=py27_0'
- !!python/unicode
  'xlwt=1.0.0=py27_0'
- !!python/unicode
  'yaml=0.1.6=0'
- !!python/unicode
  'zeromq=4.1.3=0'
- !!python/unicode
  'zlib=1.2.8=0'
- pip:
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - beautifulsoup4==4.3.2
  - blaze==0.8.0
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-console==4.1.0
  - jupyter-core==4.0.6
  - sphinx-rtd-theme==0.1.7
  - tables==3.2.0
  - wget==2.2
